# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'jarvis.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Jarvis(object):
    def setupUi(self, Jarvis):
        Jarvis.setObjectName("Jarvis")
        Jarvis.resize(830, 600)
        self.centralwidget = QtWidgets.QWidget(Jarvis)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 801, 631))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../iron man gif.gif"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(90, 520, 56, 17))
        self.pushButton.setStyleSheet("d")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(150, 520, 56, 17))
        self.pushButton_2.setObjectName("pushButton_2")
        Jarvis.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Jarvis)
        self.statusbar.setObjectName("statusbar")
        Jarvis.setStatusBar(self.statusbar)

        self.retranslateUi(Jarvis)
        QtCore.QMetaObject.connectSlotsByName(Jarvis)

    def retranslateUi(self, Jarvis):
        _translate = QtCore.QCoreApplication.translate
        Jarvis.setWindowTitle(_translate("Jarvis", "MainWindow"))
        self.pushButton.setText(_translate("Jarvis", "RUN"))
        self.pushButton_2.setText(_translate("Jarvis", "QUIT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Jarvis = QtWidgets.QMainWindow()
    ui = Ui_Jarvis()
    ui.setupUi(Jarvis)
    Jarvis.show()
    sys.exit(app.exec_())
